### ISSUE TITLE
cp: cannot stat 'ssh': No such file or directory

### ISSUE THREAD

**Issue by tinashembizi** [jtesta/ssh-mitm#4]
Good day Sir,
i am trying to run sudo cp ssh ~bogus/ but it keeps says no such directory. Kindly assist

![screenshot from 2017-05-28 17-43-31](https://cloud.githubusercontent.com/assets/17568965/26530132/ff6af84c-43ce-11e7-9c35-e41cbf162697.png)

**Comment by jtesta** [comment]
It appears that you didn't compile the sources yet.  Either way, do a "ls -l ssh" from that directory to see if the ssh client was created.

**Comment by rafikimimi** [comment]
I'm having the same issue here, kindly can you assist, I've tried to compile but it's not working.

**Comment by jtesta** [comment]
Did compilation fail?  If so, can you please paste its output?

**Comment by qingxp9** [comment]
I have the same issue using Kali 2.
The compile error is:
```
sshkey.c: In function ‘sshkey_size’:
sshkey.c:278:28: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
   return BN_num_bits(k->rsa->n);
                            ^~
sshkey.c:281:28: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
   return BN_num_bits(k->dsa->p);
                            ^~
sshkey.c: In function ‘sshkey_new’:
sshkey.c:482:11: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
       (rsa->n = BN_new()) == NULL ||
           ^~
sshkey.c:494:11: error: dereferencing pointer to incomplete type ‘DSA {aka struct dsa_st}’
       (dsa->p = BN_new()) == NULL ||
           ^~
gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.  -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DSSHDIR=\"/usr/local/etc\" -D_PATH_SSH_PROGRAM=\"/usr/local/bin/ssh\" -D_PATH_SSH_ASKPASS_DEFAULT=\"/usr/local/libexec/ssh-askpass\" -D_PATH_SFTP_SERVER=\"/usr/local/libexec/sftp-server\" -D_PATH_SSH_KEY_SIGN=\"/usr/local/libexec/ssh-keysign\" -D_PATH_SSH_PKCS11_HELPER=\"/usr/local/libexec/ssh-pkcs11-helper\" -D_PATH_SSH_PIDDIR=\"/var/run\" -D_PATH_PRIVSEP_CHROOT_DIR=\"/var/empty\" -DHAVE_CONFIG_H -c bufaux.c -o bufaux.o
gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.. -I. -I./..  -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DHAVE_CONFIG_H -c bsd-asprintf.c
gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.. -I. -I./..  -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DHAVE_CONFIG_H -c bsd-closefrom.c
gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.  -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -DSSHDIR=\"/usr/local/etc\" -D_PATH_SSH_PROGRAM=\"/usr/local/bin/ssh\" -D_PATH_SSH_ASKPASS_DEFAULT=\"/usr/local/libexec/ssh-askpass\" -D_PATH_SFTP_SERVER=\"/usr/local/libexec/sftp-server\" -D_PATH_SSH_KEY_SIGN=\"/usr/local/libexec/ssh-keysign\" -D_PATH_SSH_PKCS11_HELPER=\"/usr/local/libexec/ssh-pkcs11-helper\" -D_PATH_SSH_PIDDIR=\"/var/run\" -D_PATH_PRIVSEP_CHROOT_DIR=\"/var/empty\" -DHAVE_CONFIG_H -c bufbn.c -o bufbn.o
sshkey.c: In function ‘sshkey_parse_private_pem_fileblob’:
sshkey.c:3820:9: error: ‘EVP_R_BN_DECODE_ERROR’ undeclared (first use in this function)
    case EVP_R_BN_DECODE_ERROR:
         ^~~~~~~~~~~~~~~~~~~~~
sshkey.c:3820:9: note: each undeclared identifier is reported only once for each function it appears in
sshkey.c:3838:8: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
  if (pk->type == EVP_PKEY_RSA &&
        ^~
```

**Comment by jtesta** [comment]
This error is caused by OpenSSH not supporting OpenSSL v1.1.0.  The solution is to install the v1.0.2 development package.  In Kali, do an "apt install libssl1.0-dev".  Then try compiling it again.

I'm working on v1.1 of SSH MITM, which handles this issue automatically.

**Comment by jtesta** [comment]
I just released v1.1 of the tool.  It features an automatic installation script, which should handle all these problems.  Please give it a whirl and let me know if you have any more issues!
